// PostgreSQL embutido em memória: nunca se conecta ao Supabase/produção.
// Confere a tabela de acertos de comissão e a função que registra um acerto.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');

const lerMigration = nome => fs.readFileSync('supabase/migrations/' + nome, 'utf8').replace(/\r\n/g, '\n');
const MIGRACAO = '20261007210000_acertos_comissao.sql';

async function banco() {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema private;
    create function private.app_role() returns text language sql as $$ select current_setting('qa.role', true) $$;
    create function private.app_login() returns text language sql as $$ select current_setting('qa.login', true) $$;
    grant usage on schema private to authenticated;
    grant execute on all functions in schema private to authenticated;
    create table public.clientes (id bigint primary key, nome text);
    create table public.pedidos (
      id bigint primary key, cliente_id bigint, valor numeric, data_entrega date, vendedor text,
      status text, data_entregue_em date);
    create table public.itens_pedido (id bigint generated by default as identity primary key,
      pedido_id bigint references public.pedidos(id) on delete cascade, nome text, qtd integer);
    insert into public.clientes values (1, 'Ração & Cia'), (2, 'Sítio Boa Vista');
    insert into public.pedidos values
      (1, 1, 100,   '2026-09-01', 'vendedor', 'entregue', '2026-09-02'),
      (2, 2, 50.5,  '2026-09-03', 'vendedor', 'entregue', '2026-09-05'),
      (3, 2, 70,    '2026-09-03', 'vendedor', 'pendente', null),          -- não entregue
      (4, 1, 999,   '2026-09-04', 'admin',    'entregue', '2026-09-04'),  -- outro vendedor
      (5, 1, 30,    '2026-08-30', 'vendedor', 'entregue', '2026-08-31'),  -- fora do período
      (6, 2, 20,    '2026-09-06', 'vendedor', 'entregue', null),          -- antigo: usa a data prevista
      (7, 9, 10,    '2026-09-07', 'vendedor', 'entregue', '2026-09-07');  -- cliente apagado
    insert into public.itens_pedido(pedido_id, nome, qtd) values
      (1,'Milho',10),(1,'Farelo',4),(2,'Sal',3),(3,'Milho',7),(4,'Milho',50),(5,'Sal',1),(6,'Sal',2),(7,'Sal',1);
  `);
  await db.exec(lerMigration(MIGRACAO));
  return db;
}
const quem = (db, role, login = role) => db.exec(`reset role; select set_config('qa.role','${role}',false), set_config('qa.login','${login}',false); set role authenticated;`);
const registrar = (db, ...args) => db.query('select public.registrar_acerto($1,$2,$3::date,$4::date) as r', args);

test('Postgres: o acerto guarda, pedido a pedido, só os entregues do vendedor no período', async () => {
  const db = await banco();
  try {
    await quem(db, 'admin');
    const { r } = (await registrar(db, 'vendedor', 'semanal', '2026-09-01', '2026-09-07')).rows[0];
    assert.deepEqual(r.pedidos.map(p => p.id), [1, 2, 6, 7]);
    assert.deepEqual(r.pedidos[0], { id: 1, cliente: 'Ração & Cia', data: '2026-09-02', unidades: 14, valor: 100 });
    assert.equal(r.pedidos[2].data, '2026-09-06', 'pedido antigo sem data real usa a prevista');
    assert.equal(r.pedidos[3].cliente, 'Cliente');
    assert.equal(Number(r.unidades), 14 + 3 + 2 + 1);
    assert.equal(Number(r.total), 180.5);
    assert.equal(r.registrado_por, 'admin');
    assert.equal(r.vendedor, 'vendedor');
    assert.equal(r.tipo, 'semanal');
  } finally { await db.close(); }
});

test('Postgres: período sem entregas também pode ser acertado (zerado)', async () => {
  const db = await banco();
  try {
    await quem(db, 'admin');
    const { r } = (await registrar(db, 'vendedor', 'mensal', '2026-07-01', '2026-07-31')).rows[0];
    assert.deepEqual(r.pedidos, []);
    assert.equal(Number(r.unidades), 0);
    assert.equal(Number(r.total), 0);
  } finally { await db.close(); }
});

test('Postgres: só o administrador registra, com dados válidos', async () => {
  const db = await banco();
  try {
    for (const role of ['vendedor', 'entregador', '']) {
      await quem(db, role);
      await assert.rejects(registrar(db, 'vendedor', 'semanal', '2026-09-01', '2026-09-07'), /Só o administrador/, role);
    }
    await quem(db, 'admin');
    await assert.rejects(registrar(db, '', 'semanal', '2026-09-01', '2026-09-07'), /Escolha o vendedor/);
    await assert.rejects(registrar(db, null, 'semanal', '2026-09-01', '2026-09-07'), /Escolha o vendedor/);
    await assert.rejects(registrar(db, 'vendedor', 'anual', '2026-09-01', '2026-09-07'), /Tipo de período/);
    await assert.rejects(registrar(db, 'vendedor', 'semanal', '2026-09-07', '2026-09-01'), /Período inválido/);
    await assert.rejects(registrar(db, 'vendedor', 'semanal', null, '2026-09-01'), /Período inválido/);
    await assert.rejects(registrar(db, 'vendedor', 'mensal', '2099-01-01', '2099-01-31'), /ainda não começou/);
    await db.exec('reset role');
    assert.equal((await db.query('select count(*)::int n from public.acertos_comissao')).rows[0].n, 0);
  } finally { await db.close(); }
});

test('Postgres: ninguém grava, altera ou apaga acertos direto pela API', async () => {
  const db = await banco();
  try {
    await quem(db, 'admin');
    await registrar(db, 'vendedor', 'semanal', '2026-09-01', '2026-09-07');
    for (const sql of [
      `insert into public.acertos_comissao (vendedor,tipo,ini,fim,pedidos,unidades,total,registrado_por) values ('vendedor','semanal','2026-09-01','2026-09-07','[]',0,0,'admin')`,
      `update public.acertos_comissao set total = 0`,
      `delete from public.acertos_comissao`,
    ]) {
      await assert.rejects(db.exec(sql), /permission denied/, sql);
    }
    await db.exec('reset role');
    assert.equal((await db.query('select count(*)::int n from public.acertos_comissao')).rows[0].n, 1);
  } finally { await db.close(); }
});

test('Postgres: vendedor vê só os próprios acertos; entregador não vê nenhum', async () => {
  const db = await banco();
  try {
    await quem(db, 'admin');
    await registrar(db, 'vendedor', 'semanal', '2026-09-01', '2026-09-07');
    await registrar(db, 'admin', 'semanal', '2026-09-01', '2026-09-07');
    assert.equal((await db.query('select count(*)::int n from public.acertos_comissao')).rows[0].n, 2);
    await quem(db, 'vendedor');
    assert.deepEqual((await db.query('select vendedor from public.acertos_comissao')).rows, [{ vendedor: 'vendedor' }]);
    await quem(db, 'vendedor', 'outro');
    assert.equal((await db.query('select count(*)::int n from public.acertos_comissao')).rows[0].n, 0);
    await quem(db, 'entregador');
    assert.equal((await db.query('select count(*)::int n from public.acertos_comissao')).rows[0].n, 0);
  } finally { await db.close(); }
});

test('Postgres: acerto refeito é um registro novo; o antigo fica no histórico', async () => {
  const db = await banco();
  try {
    await quem(db, 'admin');
    await registrar(db, 'vendedor', 'semanal', '2026-09-01', '2026-09-07');
    await db.exec('reset role');
    await db.exec(`update public.itens_pedido set qtd = 8 where pedido_id = 1 and nome = 'Milho'`); // devolução de 2
    await quem(db, 'admin');
    await registrar(db, 'vendedor', 'semanal', '2026-09-01', '2026-09-07');
    const linhas = (await db.query('select unidades from public.acertos_comissao order by id')).rows.map(r => Number(r.unidades));
    assert.deepEqual(linhas, [20, 18]);
  } finally { await db.close(); }
});

test('Postgres: a migração não toca nos pedidos', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated; create schema private;
      create function private.app_role() returns text language sql as $$ select null::text $$;
      create function private.app_login() returns text language sql as $$ select null::text $$;
      create table public.clientes (id bigint primary key, nome text);
      create table public.pedidos (id bigint primary key, cliente_id bigint, valor numeric, data_entrega date, vendedor text, status text, data_entregue_em date);
      create table public.itens_pedido (id bigint primary key, pedido_id bigint, nome text, qtd integer);
      insert into public.pedidos values (1, 1, 10, '2026-09-01', 'vendedor', 'entregue', '2026-09-01');`);
    const antes = JSON.stringify((await db.query('select * from public.pedidos')).rows);
    await db.exec(lerMigration(MIGRACAO));
    assert.equal(JSON.stringify((await db.query('select * from public.pedidos')).rows), antes);
    assert.match(lerMigration(MIGRACAO), /revoke all on function public\.registrar_acerto\(text, text, date, date\) from public, anon;/);
  } finally { await db.close(); }
});
