// PostgreSQL embutido em memória: nunca se conecta ao Supabase/produção.
// Aplica as migrations reais na ordem e confere que "cheque" passa a ser aceito
// como forma de recebimento (entrega completa e parcial), sem afrouxar o resto.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');

const lerMigration = nome => fs.readFileSync('supabase/migrations/' + nome, 'utf8').replace(/\r\n/g, '\n');
const fatia = (texto, inicio, fimMarcador) => {
  const i = texto.indexOf(inicio);
  assert.ok(i >= 0, 'trecho não encontrado: ' + inicio);
  const f = texto.indexOf(fimMarcador, i);
  assert.ok(f >= 0, 'fim não encontrado: ' + fimMarcador);
  return texto.slice(i, f + fimMarcador.length);
};
const CHEQUE = '20261007180000_cheque_forma_real.sql';

// Banco como está em produção ANTES do cheque (migrations anteriores aplicadas).
async function bancoAntesDoCheque() {
  const db = new PGlite();
  const harden = lerMigration('20260813152904_harden_auth_and_data.sql');
  const rls = lerMigration('20260813153429_optimize_rls_policies.sql');
  const atomica = lerMigration('20260908154035_atomic_orders_and_restricted_costs.sql');
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema private;
    create function private.app_role() returns text language sql as $$ select current_setting('qa.role', true) $$;
    create function private.app_login() returns text language sql as $$ select current_setting('qa.login', true) $$;
    create table public.pedidos (
      id bigint primary key, cliente_id bigint, descricao text, valor numeric, data_entrega date, data_vencimento date,
      vendedor text, forma_pagamento text, prazo_dias integer, prazos_boleto text, status text, status_pagamento text,
      forma_pagamento_real text, data_pagamento date, data_entregue_em date, observacao text);
    create table public.itens_pedido (
      id bigint generated by default as identity primary key,
      pedido_id bigint references public.pedidos(id) on delete cascade,
      produto_id bigint, nome text, qtd integer, preco_unit numeric, preco_catalogo numeric,
      constraint itens_qtd_check check (qtd > 0));
    alter table public.pedidos enable row level security;
    alter table public.itens_pedido enable row level security;
    grant usage on schema private to authenticated;
    grant execute on all functions in schema private to authenticated;
    grant select, insert, update, delete on public.pedidos, public.itens_pedido to authenticated;
  `);
  // A restrição de produção (a mesma da migration de endurecimento).
  await db.exec(fatia(harden, 'add constraint pedidos_forma_pagamento_real_check', "'pix'))").replace(/^/, 'alter table public.pedidos ') + ';');
  for (const politica of ['pedidos_select', 'pedidos_update']) await db.exec(fatia(rls, 'create policy ' + politica, ';'));
  await db.exec(fatia(rls, 'create policy itens_select', ';'));
  await db.exec(fatia(rls, 'create or replace function public.restringir_update_entregador()', '$$;'));
  await db.exec(fatia(harden, 'drop trigger if exists pedidos_restringir_update_entregador', 'restringir_update_entregador();'));
  await db.exec(fatia(atomica, 'create or replace function private.validar_total_pedido()', 'itens_total_consistente after insert or update or delete on public.itens_pedido\n  deferrable initially deferred for each row execute function private.validar_total_pedido();'));
  await db.exec(lerMigration('20260909185425_preserve_prepaid_delivery.sql'));
  await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
  return db;
}

async function novoPedido(db, id = 1) {
  await db.exec('reset role; delete from public.pedidos;');
  await db.exec(`
    begin;
    insert into public.pedidos(id,cliente_id,descricao,valor,data_entrega,vendedor,forma_pagamento,status)
      values (${id},1,'10x Milho 60kg, 4x Farelo',200,'2026-09-20','vendedor','cheque','pendente');
    insert into public.itens_pedido(pedido_id,produto_id,nome,qtd,preco_unit,preco_catalogo) values
      (${id},1,'Milho 60kg',10,10,10),(${id},2,'Farelo',4,25,25);
    commit;
  `);
  const itens = (await db.query('select id from public.itens_pedido where pedido_id=$1 order by id', [id])).rows;
  return { milho: itens[0].id, farelo: itens[1].id };
}

const quem = (db, role) => db.exec(`select set_config('qa.role','${role}',false), set_config('qa.login','${role}',false); set role authenticated;`);
const dados = extra => JSON.stringify({ data_entregue_em: '2026-10-07', observacao: '', status_pagamento: 'pago', data_pagamento: '2026-10-07', ...extra });
const completa = (db, id, extra) => db.query('select public.concluir_entrega($1,$2::jsonb) as r', [id, dados(extra)]);
const parcial = (db, id, itens, extra) => db.query('select public.concluir_entrega_parcial($1,$2::jsonb,$3::jsonb) as r', [id, dados(extra), JSON.stringify(itens)]);

test('Postgres: antes da migração, cheque é recusado; depois, aceito (entrega completa)', async () => {
  const db = await bancoAntesDoCheque();
  try {
    await novoPedido(db);
    await quem(db, 'entregador');
    await assert.rejects(completa(db, 1, { forma_pagamento_real: 'cheque' }), /forma e a data/, 'banco antigo recusa cheque');
    await db.exec('reset role');

    await db.exec(lerMigration(CHEQUE));
    await quem(db, 'entregador');
    const { r } = (await completa(db, 1, { forma_pagamento_real: 'cheque' })).rows[0];
    assert.equal(r.status, 'entregue');
    assert.equal(r.status_pagamento, 'pago');
    assert.equal(r.forma_pagamento_real, 'cheque');
    assert.equal(r.data_pagamento, '2026-10-07');
  } finally { await db.close(); }
});

test('Postgres: cheque na entrega parcial também é aceito e guarda a forma', async () => {
  const db = await bancoAntesDoCheque();
  try {
    const ids = await novoPedido(db);
    const itens = [{ id: ids.milho, qtd_entregue: 6 }, { id: ids.farelo, qtd_entregue: 4 }];
    await quem(db, 'entregador');
    await assert.rejects(parcial(db, 1, itens, { forma_pagamento_real: 'cheque' }), /forma e a data/);
    await db.exec('reset role');

    await db.exec(lerMigration(CHEQUE));
    await quem(db, 'admin');
    const { r } = (await parcial(db, 1, itens, { forma_pagamento_real: 'cheque' })).rows[0];
    assert.equal(Number(r.valor), 160);
    assert.equal(r.status_pagamento, 'pago');
    assert.equal(r.forma_pagamento_real, 'cheque');
    await db.exec('reset role');
    assert.equal((await db.query('select forma_pagamento_real f from public.pedidos')).rows[0].f, 'cheque');
  } finally { await db.close(); }
});

test('Postgres: depois do cheque, o resto continua exigido (forma inválida, sem data, sem forma)', async () => {
  const db = await bancoAntesDoCheque();
  try {
    await db.exec(lerMigration(CHEQUE));
    const ids = await novoPedido(db);
    const itens = [{ id: ids.milho, qtd_entregue: 10 }, { id: ids.farelo, qtd_entregue: 4 }];
    await quem(db, 'entregador');
    for (const forma of ['boleto', 'avista', 'CHEQUE', 'cheque ', '', null]) {
      await assert.rejects(completa(db, 1, { forma_pagamento_real: forma }), /forma e a data/, 'completa: ' + JSON.stringify(forma));
      await assert.rejects(parcial(db, 1, itens, { forma_pagamento_real: forma }), /forma e a data/, 'parcial: ' + JSON.stringify(forma));
    }
    await assert.rejects(completa(db, 1, { forma_pagamento_real: 'cheque', data_pagamento: null }), /forma e a data/);
    await assert.rejects(parcial(db, 1, itens, { forma_pagamento_real: 'cheque', data_pagamento: null }), /forma e a data/);
    await db.exec('reset role');
    const p = (await db.query('select status, status_pagamento, forma_pagamento_real from public.pedidos')).rows[0];
    assert.deepEqual(p, { status: 'pendente', status_pagamento: null, forma_pagamento_real: null }, 'nada foi gravado');
  } finally { await db.close(); }
});

test('Postgres: a restrição da tabela aceita só dinheiro, pix e cheque', async () => {
  const db = await bancoAntesDoCheque();
  try {
    await db.exec(lerMigration(CHEQUE));
    await novoPedido(db);
    for (const ok of ['dinheiro', 'pix', 'cheque']) {
      await db.exec(`update public.pedidos set forma_pagamento_real='${ok}'`);
    }
    await db.exec('update public.pedidos set forma_pagamento_real=null');
    for (const ruim of ['boleto', 'Cheque', 'cartao']) {
      await assert.rejects(db.exec(`update public.pedidos set forma_pagamento_real='${ruim}'`), /pedidos_forma_pagamento_real_check/, ruim);
    }
  } finally { await db.close(); }
});

test('Postgres: pedidos existentes ficam intactos e as permissões das funções não mudam', async () => {
  const db = await bancoAntesDoCheque();
  try {
    await novoPedido(db);
    await db.exec(`update public.pedidos set status='entregue', status_pagamento='pago', forma_pagamento_real='dinheiro', data_pagamento='2026-09-01'`);
    const antes = JSON.stringify((await db.query('select * from public.pedidos order by id')).rows);
    const acl = async () => (await db.query(`select p.proname, p.prosecdef, p.proconfig::text cfg, has_function_privilege('anon', p.oid, 'execute') anon, has_function_privilege('authenticated', p.oid, 'execute') auth
      from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('concluir_entrega','concluir_entrega_parcial') order by 1`)).rows;
    const aclAntes = await acl();
    assert.equal(aclAntes.length, 2);
    await db.exec(lerMigration(CHEQUE));
    assert.equal(JSON.stringify((await db.query('select * from public.pedidos order by id')).rows), antes);
    assert.deepEqual(await acl(), aclAntes, 'segurança (security definer/invoker, search_path, quem executa) idêntica');
  } finally { await db.close(); }
});

test('Migração do cheque só muda a lista de formas: corpo das funções igual ao das migrations anteriores', () => {
  const norm = t => t.replace(/\s+/g, ' ').trim();
  const cheque = lerMigration(CHEQUE);
  const corpo = (sql, nome) => norm(fatia(sql, 'create or replace function public.' + nome + '(', 'end; $$;'));
  const volta = t => t.replace("('dinheiro','pix','cheque')", "('dinheiro','pix')");
  assert.equal(volta(corpo(cheque, 'concluir_entrega')), corpo(lerMigration('20260909185425_preserve_prepaid_delivery.sql'), 'concluir_entrega'));
  assert.equal(volta(corpo(cheque, 'concluir_entrega_parcial')), corpo(lerMigration('20260928170000_partial_delivery.sql'), 'concluir_entrega_parcial'));
});
