// PostgreSQL embutido em memória: nunca se conecta ao Supabase/produção.
// Aplica as migrations reais na ordem e confere que o entregador só consegue
// concluir entregas pelas funções do aplicativo, com datas recentes.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');

const lerMigration = nome => fs.readFileSync('supabase/migrations/' + nome, 'utf8').replace(/\r\n/g, '\n');
const fatia = (texto, inicio, fimMarcador) => {
  const i = texto.indexOf(inicio);
  assert.ok(i >= 0, 'trecho não encontrado: ' + inicio);
  const f = texto.indexOf(fimMarcador, i);
  assert.ok(f >= 0, 'fim não encontrado: ' + fimMarcador);
  return texto.slice(i, f + fimMarcador.length);
};
const NOVA = '20261007200000_entregador_so_pelas_funcoes.sql';

// Banco como está em produção hoje (até a migração do cheque).
async function bancoAtual() {
  const db = new PGlite();
  const harden = lerMigration('20260813152904_harden_auth_and_data.sql');
  const rls = lerMigration('20260813153429_optimize_rls_policies.sql');
  const atomica = lerMigration('20260908154035_atomic_orders_and_restricted_costs.sql');
  const dataReal = lerMigration('20260828165707_add_actual_delivery_date.sql');
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema private;
    create function private.app_role() returns text language sql as $$ select current_setting('qa.role', true) $$;
    create function private.app_login() returns text language sql as $$ select current_setting('qa.login', true) $$;
    create table public.pedidos (
      id bigint primary key, cliente_id bigint, descricao text, valor numeric, data_entrega date, data_vencimento date,
      vendedor text, forma_pagamento text, prazo_dias integer, prazos_boleto text, status text, status_pagamento text,
      forma_pagamento_real text, data_pagamento date, data_entregue_em date, observacao text, chave_criacao text);
    create table public.itens_pedido (
      id bigint generated by default as identity primary key,
      pedido_id bigint references public.pedidos(id) on delete cascade,
      produto_id bigint, nome text, qtd integer, preco_unit numeric, preco_catalogo numeric,
      constraint itens_qtd_check check (qtd > 0));
    alter table public.pedidos enable row level security;
    alter table public.itens_pedido enable row level security;
    grant usage on schema private to authenticated;
    grant select, insert, update, delete on public.pedidos, public.itens_pedido to authenticated;
  `);
  for (const politica of ['pedidos_select', 'pedidos_update']) await db.exec(fatia(rls, 'create policy ' + politica, ';'));
  await db.exec(fatia(rls, 'create policy itens_select', ';'));
  await db.exec(fatia(rls, 'create or replace function public.restringir_update_entregador()', '$$;'));
  await db.exec(fatia(harden, 'drop trigger if exists pedidos_restringir_update_entregador', 'restringir_update_entregador();'));
  // Os outros gatilhos de produção que mexem nas mesmas colunas, na mesma ordem.
  await db.exec(dataReal.slice(dataReal.indexOf('create or replace function private.definir_data_entrega_real()')));
  await db.exec(fatia(atomica, 'create or replace function private.proteger_pagamento_vendedor()', 'execute function private.proteger_pagamento_vendedor();'));
  await db.exec(fatia(atomica, 'create or replace function private.validar_total_pedido()', 'itens_total_consistente after insert or update or delete on public.itens_pedido\n  deferrable initially deferred for each row execute function private.validar_total_pedido();'));
  await db.exec(lerMigration('20260909185425_preserve_prepaid_delivery.sql'));
  await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
  await db.exec(fatia(harden, 'add constraint pedidos_forma_pagamento_real_check', "'pix'))").replace(/^/, 'alter table public.pedidos ') + ';');
  await db.exec(lerMigration('20261007180000_cheque_forma_real.sql'));
  await db.exec('grant execute on all functions in schema private to authenticated;');
  return db;
}

async function hojeBrasil(db, dias = 0) {
  return (await db.query(`select to_char((statement_timestamp() at time zone 'America/Sao_Paulo')::date + $1::int, 'YYYY-MM-DD') d`, [dias])).rows[0].d;
}

async function pedidos(db) {
  await db.exec('reset role; delete from public.pedidos;');
  await db.exec(`
    begin;
    insert into public.pedidos(id,cliente_id,descricao,valor,data_entrega,vendedor,forma_pagamento,status) values
      (1,1,'10x Milho 60kg, 4x Farelo',200,'2026-09-20','vendedor','avista','pendente'),
      (2,1,'1x Sal',5,'2026-09-20','vendedor','avista','pendente');
    insert into public.itens_pedido(pedido_id,produto_id,nome,qtd,preco_unit,preco_catalogo) values
      (1,1,'Milho 60kg',10,10,10),(1,2,'Farelo',4,25,25),(2,3,'Sal',1,5,5);
    commit;
  `);
  return (await db.query('select id from public.itens_pedido where pedido_id=1 order by id')).rows.map(r => r.id);
}

const quem = (db, role) => db.exec(`reset role; select set_config('qa.role','${role}',false), set_config('qa.login','${role}',false); set role authenticated;`);
const dados = (hoje, extra) => JSON.stringify({ data_entregue_em: hoje, observacao: '', status_pagamento: 'pago', forma_pagamento_real: 'dinheiro', data_pagamento: hoje, ...extra });
const completa = (db, id, d) => db.query('select public.concluir_entrega($1,$2::jsonb) as r', [id, d]);
const parcial = (db, id, d, itens) => db.query('select public.concluir_entrega_parcial($1,$2::jsonb,$3::jsonb) as r', [id, d, JSON.stringify(itens)]);
const linha = async (db, id) => { await db.exec('reset role'); return (await db.query('select * from public.pedidos where id=$1', [id])).rows[0]; };

test('Postgres: antes, o entregador conseguia entregar por PATCH direto sem informar pagamento; agora não', async () => {
  const db = await bancoAtual();
  try {
    await pedidos(db);
    await quem(db, 'entregador');
    await db.exec("update public.pedidos set status='entregue' where id=1");
    assert.equal((await linha(db, 1)).status, 'entregue', 'a brecha existia: entregue sem status de pagamento');
    assert.equal((await linha(db, 1)).status_pagamento, null);

    await db.exec(lerMigration(NOVA));
    await pedidos(db);
    await quem(db, 'entregador');
    for (const sql of [
      "update public.pedidos set status='entregue' where id=1",
      "update public.pedidos set status='entregue', status_pagamento='pago', forma_pagamento_real='pix', data_pagamento=current_date where id=1",
      "update public.pedidos set observacao='x' where id=1",
    ]) {
      await assert.rejects(db.exec(sql), /só pode concluir a entrega pelo aplicativo/, sql);
    }
    assert.equal((await linha(db, 1)).status, 'pendente');
  } finally { await db.close(); }
});

test('Postgres: pelo aplicativo (funções) o entregador continua entregando normalmente', async () => {
  const db = await bancoAtual();
  try {
    await db.exec(lerMigration(NOVA));
    const [milho, farelo] = await pedidos(db);
    const hoje = await hojeBrasil(db);
    await quem(db, 'entregador');
    const { r } = (await completa(db, 2, dados(hoje, { forma_pagamento_real: 'cheque' }))).rows[0];
    assert.equal(r.status, 'entregue');
    assert.equal(r.forma_pagamento_real, 'cheque');
    assert.equal(r.data_entregue_em, hoje);
    // Reenvio (resposta perdida) continua devolvendo o pedido sem erro.
    assert.equal((await completa(db, 2, dados(hoje))).rows[0].r.status, 'entregue');

    await quem(db, 'entregador');
    const p = (await parcial(db, 1, dados(hoje, { status_pagamento: 'pendente', forma_pagamento_real: null, data_pagamento: null }),
      [{ id: milho, qtd_entregue: 8 }, { id: farelo, qtd_entregue: 4 }])).rows[0].r;
    assert.equal(Number(p.valor), 180);
    assert.equal(p.status_pagamento, 'pendente');
  } finally { await db.close(); }
});

test('Postgres: data da entrega do entregador — até 7 dias atrás (sem internet) passa; mais antiga não', async () => {
  const db = await bancoAtual();
  try {
    await db.exec(lerMigration(NOVA));
    await pedidos(db);
    const sete = await hojeBrasil(db, -7), oito = await hojeBrasil(db, -8), hoje = await hojeBrasil(db);
    await quem(db, 'entregador');
    await assert.rejects(completa(db, 1, dados(oito, { data_pagamento: hoje })), /mais de 7 dias/);
    await assert.rejects(completa(db, 1, dados(await hojeBrasil(db, 1), { data_pagamento: hoje })), /futuro/);
    assert.equal((await linha(db, 1)).status, 'pendente', 'nada gravado');
    await quem(db, 'entregador');
    const { r } = (await completa(db, 1, dados(sete))).rows[0];
    assert.equal(r.data_entregue_em, sete);
    assert.equal(r.data_pagamento, sete);
  } finally { await db.close(); }
});

test('Postgres: data do pagamento do entregador — hoje ou até 7 dias, nunca no futuro', async () => {
  const db = await bancoAtual();
  try {
    await db.exec(lerMigration(NOVA));
    await pedidos(db);
    const hoje = await hojeBrasil(db);
    await quem(db, 'entregador');
    await assert.rejects(completa(db, 1, dados(hoje, { data_pagamento: await hojeBrasil(db, -8) })), /Data do pagamento inválida/);
    await assert.rejects(completa(db, 1, dados(hoje, { data_pagamento: await hojeBrasil(db, 1) })), /Data do pagamento inválida/);
    await assert.rejects(completa(db, 1, dados(hoje, { data_pagamento: '2020-01-01' })), /Data do pagamento inválida/);
    assert.equal((await completa(db, 1, dados(hoje))).rows[0].r.data_pagamento, hoje);
  } finally { await db.close(); }
});

test('Postgres: pedido pago adiantado (data antiga) ainda pode ser entregue pelo entregador', async () => {
  const db = await bancoAtual();
  try {
    await db.exec(lerMigration(NOVA));
    await pedidos(db);
    await db.exec(`update public.pedidos set status_pagamento='pago', forma_pagamento_real='pix', data_pagamento='2026-01-15' where id=1`);
    const hoje = await hojeBrasil(db);
    await quem(db, 'entregador');
    const { r } = (await completa(db, 1, dados(hoje, { status_pagamento: 'pendente', forma_pagamento_real: null, data_pagamento: null }))).rows[0];
    assert.equal(r.status, 'entregue');
    assert.equal(r.data_pagamento, '2026-01-15', 'a data antiga do pagamento é preservada, não conta como data nova');
  } finally { await db.close(); }
});

test('Postgres: a marca da função vale só para o pedido e só durante a função', async () => {
  const db = await bancoAtual();
  try {
    await db.exec(lerMigration(NOVA));
    await pedidos(db);
    const hoje = await hojeBrasil(db);
    await quem(db, 'entregador');
    // Marca de outro pedido não libera este.
    await assert.rejects(db.exec("begin; select set_config('kg.concluir_entrega','2',true); update public.pedidos set status='entregue' where id=1; commit;"), /pelo aplicativo/);
    await db.exec('rollback');
    // Depois da função, na mesma transação, um PATCH direto continua bloqueado.
    await quem(db, 'entregador');
    await db.exec('begin');
    await completa(db, 2, dados(hoje));
    await assert.rejects(db.exec("update public.pedidos set status='entregue' where id=1"), /pelo aplicativo/);
    await db.exec('rollback');
  } finally { await db.close(); }
});

test('Postgres: administrador e vendedor não mudam', async () => {
  const db = await bancoAtual();
  try {
    await db.exec(lerMigration(NOVA));
    await pedidos(db);
    await quem(db, 'admin');
    await db.exec("update public.pedidos set status='entregue', data_entregue_em='2026-01-10', status_pagamento='pago', forma_pagamento_real='pix', data_pagamento='2026-01-10' where id=1");
    const p = await linha(db, 1);
    assert.equal(p.data_entregue_em.toISOString().slice(0, 10), '2026-01-10', 'admin pode registrar entrega antiga');
    await quem(db, 'vendedor');
    await db.exec("update public.pedidos set observacao='ligar antes' where id=2");
    assert.equal((await linha(db, 2)).observacao, 'ligar antes');
  } finally { await db.close(); }
});

test('Postgres: nenhum pedido existente muda e as permissões das funções ficam iguais', async () => {
  const db = await bancoAtual();
  try {
    await pedidos(db);
    await db.exec(`update public.pedidos set status='entregue', status_pagamento='pago', forma_pagamento_real='dinheiro', data_pagamento='2026-09-01' where id=2`);
    const antes = JSON.stringify((await db.query('select * from public.pedidos order by id')).rows);
    const acl = async () => (await db.query(`select p.proname, p.prosecdef, p.proconfig::text cfg, p.proacl::text acl
      from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'
      and p.proname in ('concluir_entrega','concluir_entrega_parcial','restringir_update_entregador') order by 1`)).rows;
    const aclAntes = await acl();
    assert.equal(aclAntes.length, 3);
    await db.exec(lerMigration(NOVA));
    assert.equal(JSON.stringify((await db.query('select * from public.pedidos order by id')).rows), antes);
    assert.deepEqual(await acl(), aclAntes);
  } finally { await db.close(); }
});

test('Migração: funções iguais às do cheque, só com a marca antes e depois do UPDATE', () => {
  const norm = t => t.replace(/\s+/g, ' ').trim();
  const nova = lerMigration(NOVA), cheque = lerMigration('20261007180000_cheque_forma_real.sql');
  const sem = t => t.replace(/ *-- Marca, só para este UPDATE[^\n]*\n *-- entregador recusa[^\n]*\n/g, '')
    .replace(/ *perform pg_catalog\.set_config\('kg\.concluir_entrega', (p_id::text|''), true\);\n/g, '');
  for (const nome of ['concluir_entrega', 'concluir_entrega_parcial']) {
    const corpo = sql => fatia(sql, 'create or replace function public.' + nome + '(', 'end; $$;');
    assert.equal((corpo(nova).match(/kg\.concluir_entrega/g) || []).length, 2, nome + ': marca e limpa');
    assert.equal(norm(sem(corpo(nova))), norm(corpo(cheque)), nome);
  }
});
