// PostgreSQL embutido em memória: nunca se conecta ao Supabase/produção.
// Usa as regras reais do projeto (RLS, gatilhos, concluir_entrega) lidas das
// migrations e aplica por cima a migration de entrega parcial.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');

const lerMigration = nome => fs.readFileSync('supabase/migrations/' + nome, 'utf8').replace(/\r\n/g, '\n');
const fatia = (texto, inicio, fimMarcador, incluirFim = true) => {
  const i = texto.indexOf(inicio);
  assert.ok(i >= 0, 'trecho não encontrado: ' + inicio);
  const f = texto.indexOf(fimMarcador, i);
  assert.ok(f >= 0, 'fim não encontrado: ' + fimMarcador);
  return texto.slice(i, incluirFim ? f + fimMarcador.length : f);
};

async function bancoComRegrasAtuais() {
  const db = new PGlite();
  const harden = lerMigration('20260813152904_harden_auth_and_data.sql');
  const rls = lerMigration('20260813153429_optimize_rls_policies.sql');
  const atomica = lerMigration('20260908154035_atomic_orders_and_restricted_costs.sql');
  await db.exec(`
    create role anon; create role authenticated;
    create schema private;
    create function private.app_role() returns text language sql as $$ select current_setting('qa.role', true) $$;
    create function private.app_login() returns text language sql as $$ select current_setting('qa.login', true) $$;
    create table public.pedidos (
      id bigint primary key, cliente_id bigint, descricao text, valor numeric, data_entrega date, data_vencimento date,
      vendedor text, forma_pagamento text, prazo_dias integer, prazos_boleto text, status text, status_pagamento text,
      forma_pagamento_real text, data_pagamento date, data_entregue_em date, observacao text);
    create table public.itens_pedido (
      id bigint generated by default as identity primary key,
      pedido_id bigint references public.pedidos(id) on delete cascade,
      produto_id bigint, nome text, qtd integer, preco_unit numeric, preco_catalogo numeric,
      constraint itens_qtd_check check (qtd > 0));
    alter table public.pedidos enable row level security;
    alter table public.itens_pedido enable row level security;
    grant usage on schema private to authenticated;
    grant execute on all functions in schema private to authenticated;
    grant select, insert, update, delete on public.pedidos, public.itens_pedido to authenticated;
  `);
  for (const politica of ['pedidos_select', 'pedidos_update']) {
    await db.exec(fatia(rls, 'create policy ' + politica, ';'));
  }
  await db.exec(fatia(rls, 'create policy itens_select', ';'));
  // Gatilho do entregador e verificação de total, exatamente como estão hoje.
  await db.exec(fatia(rls, 'create or replace function public.restringir_update_entregador()', '$$;'));
  await db.exec(fatia(harden, 'drop trigger if exists pedidos_restringir_update_entregador', 'restringir_update_entregador();'));
  await db.exec(fatia(atomica, 'create or replace function private.validar_total_pedido()', 'itens_total_consistente after insert or update or delete on public.itens_pedido\n  deferrable initially deferred for each row execute function private.validar_total_pedido();'));
  await db.exec(lerMigration('20260909185425_preserve_prepaid_delivery.sql'));
  return db;
}

async function novoPedido(db, { id = 1, status_pagamento = null, forma_pagamento_real = null, data_pagamento = null } = {}) {
  await db.exec('reset role; delete from public.pedidos;');
  await db.exec(`
    begin;
    insert into public.pedidos(id,cliente_id,descricao,valor,data_entrega,vendedor,forma_pagamento,status,status_pagamento,forma_pagamento_real,data_pagamento)
      values (${id},1,'10x Milho 60kg, 4x Farelo',200,'2026-09-20','vendedor','boleto','pendente',
        ${status_pagamento ? "'" + status_pagamento + "'" : 'null'},${forma_pagamento_real ? "'" + forma_pagamento_real + "'" : 'null'},${data_pagamento ? "'" + data_pagamento + "'" : 'null'});
    insert into public.itens_pedido(pedido_id,produto_id,nome,qtd,preco_unit,preco_catalogo) values
      (${id},1,'Milho 60kg',10,10,10),(${id},2,'Farelo',4,25,25);
    commit;
  `);
  const itens = (await db.query('select id, nome from public.itens_pedido where pedido_id=$1 order by id', [id])).rows;
  return { milho: itens[0].id, farelo: itens[1].id };
}

const quem = (db, role) => db.exec(`select set_config('qa.role','${role}',false), set_config('qa.login','${role}',false); set role authenticated;`);
const dados = extra => JSON.stringify({ data_entregue_em: '2026-09-21', observacao: '', status_pagamento: 'pendente', ...extra });
const parcial = (db, id, itens, extra) => db.query('select public.concluir_entrega_parcial($1,$2::jsonb,$3::jsonb) as r', [id, dados(extra), JSON.stringify(itens)]);

test('Postgres: entrega parcial reduz itens, recalcula o valor e guarda o pedido original', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    const antes = await novoPedido(db);
    // Antes da migration, o entregador não consegue mudar valor nem itens por conta própria.
    await quem(db, 'entregador');
    await assert.rejects(db.exec("update public.pedidos set valor=1, status='entregue' where id=1"), /entregador só pode concluir/);
    await db.exec('reset role');

    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    assert.deepEqual((await db.query('select count(*)::int n from public.itens_pedido where qtd_pedida is not null')).rows[0], { n: 0 }, 'pedidos existentes ficam intactos');

    const ids = await novoPedido(db);
    assert.equal(ids.milho, antes.milho + 2);
    await quem(db, 'entregador');
    const { r } = (await parcial(db, 1, [{ id: ids.milho, qtd_entregue: 8 }, { id: ids.farelo, qtd_entregue: 0 }])).rows[0];
    assert.equal(r.status, 'entregue');
    assert.equal(Number(r.valor), 80);
    assert.equal(r.descricao, '8x Milho 60kg');
    assert.equal(r.data_entregue_em, '2026-09-21');
    assert.equal(r.status_pagamento, 'pendente');
    assert.deepEqual(r.itens.map(i => [i.nome, i.qtd, i.qtd_pedida]), [['Milho 60kg', 8, 10]], 'item zerado sai; o outro guarda o que foi pedido');

    await db.exec('reset role');
    const itens = (await db.query('select nome, qtd, qtd_pedida from public.itens_pedido order by id')).rows;
    assert.deepEqual(itens, [{ nome: 'Milho 60kg', qtd: 8, qtd_pedida: 10 }]);
    const pedido = (await db.query('select valor, descricao, status from public.pedidos')).rows[0];
    assert.equal(Number(pedido.valor), 80);
    assert.equal(pedido.status, 'entregue');
  } finally { await db.close(); }
});

test('Postgres: entrega parcial em vários itens e reenvio idempotente', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    const ids = await novoPedido(db);
    await quem(db, 'admin');
    const itens = [{ id: ids.milho, qtd_entregue: 9 }, { id: ids.farelo, qtd_entregue: 3 }];
    const { r } = (await parcial(db, 1, itens)).rows[0];
    assert.equal(Number(r.valor), 9 * 10 + 3 * 25);
    assert.equal(r.descricao, '9x Milho 60kg, 3x Farelo');
    // Reenvio (resposta perdida): devolve o mesmo resultado e não reduz de novo.
    const segundo = (await parcial(db, 1, [{ id: ids.milho, qtd_entregue: 1 }, { id: ids.farelo, qtd_entregue: 1 }], { data_entregue_em: '2026-09-25' })).rows[0].r;
    assert.equal(Number(segundo.valor), 165);
    assert.equal(segundo.data_entregue_em, '2026-09-21');
    assert.deepEqual(segundo.itens.map(i => i.qtd), [9, 3]);
  } finally { await db.close(); }
});

test('Postgres: entrega completa pela função nova não marca quantidade pedida', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    const ids = await novoPedido(db);
    await quem(db, 'entregador');
    const { r } = (await parcial(db, 1, [{ id: ids.milho, qtd_entregue: 10 }, { id: ids.farelo, qtd_entregue: 4 }])).rows[0];
    assert.equal(Number(r.valor), 200);
    assert.equal(r.descricao, '10x Milho 60kg, 4x Farelo');
    assert.ok(r.itens.every(i => i.qtd_pedida === null));
  } finally { await db.close(); }
});

test('Postgres: entrega parcial recusa dados inválidos e não altera nada', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    const ids = await novoPedido(db);
    await quem(db, 'entregador');
    const ok = [{ id: ids.milho, qtd_entregue: 5 }, { id: ids.farelo, qtd_entregue: 2 }];
    const casos = [
      [[{ id: ids.milho, qtd_entregue: 11 }, ok[1]], /inválida/],            // mais do que o pedido
      [[{ id: ids.milho, qtd_entregue: -1 }, ok[1]], /inválida/],
      [[{ id: ids.milho, qtd_entregue: 2.5 }, ok[1]], /inteiro/],
      [[{ id: ids.milho, qtd_entregue: 0 }, { id: ids.farelo, qtd_entregue: 0 }], /Nada foi entregue/],
      [[ok[0]], /cada item/],                                                // falta um item
      [[ok[0], ok[0]], /cada item/],                                         // item repetido
      [[ok[0], { id: 999999, qtd_entregue: 1 }], /inteiro|cada item/],       // item de outro pedido
      [[], /cada item/],
      [{ id: 1 }, /cada item/],
    ];
    for (const [itens, erro] of casos) {
      await assert.rejects(parcial(db, 1, itens), erro, JSON.stringify(itens));
    }
    await assert.rejects(parcial(db, 1, ok, { status_pagamento: 'talvez' }), /resultado do recebimento/);
    await assert.rejects(parcial(db, 1, ok, { status_pagamento: 'pago' }), /forma e a data/);
    await assert.rejects(parcial(db, 404, ok), /não encontrado/);
    await db.exec('reset role');
    const p = (await db.query('select status, valor from public.pedidos')).rows[0];
    assert.equal(p.status, 'pendente');
    assert.equal(Number(p.valor), 200);
    assert.deepEqual((await db.query('select qtd, qtd_pedida from public.itens_pedido order by id')).rows, [{ qtd: 10, qtd_pedida: null }, { qtd: 4, qtd_pedida: null }]);
  } finally { await db.close(); }
});

test('Postgres: pedido pago adiantado não aceita entrega parcial, mas aceita completa', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    const ids = await novoPedido(db, { status_pagamento: 'pago', forma_pagamento_real: 'pix', data_pagamento: '2026-09-01' });
    for (const role of ['entregador', 'admin']) {
      await quem(db, role);
      await assert.rejects(parcial(db, 1, [{ id: ids.milho, qtd_entregue: 8 }, { id: ids.farelo, qtd_entregue: 4 }]), /Pedido já pago/);
      await db.exec('reset role');
    }
    await quem(db, 'entregador');
    const { r } = (await parcial(db, 1, [{ id: ids.milho, qtd_entregue: 10 }, { id: ids.farelo, qtd_entregue: 4 }], { status_pagamento: 'pendente' })).rows[0];
    assert.equal(r.status, 'entregue');
    assert.equal(r.status_pagamento, 'pago', 'pagamento antecipado preservado');
    assert.equal(r.forma_pagamento_real, 'pix');
    assert.equal(r.data_pagamento, '2026-09-01');
  } finally { await db.close(); }
});

test('Postgres: recebimento no ato da entrega parcial e permissões', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    const ids = await novoPedido(db);
    const itens = [{ id: ids.milho, qtd_entregue: 5 }, { id: ids.farelo, qtd_entregue: 4 }];
    for (const role of ['vendedor', 'anon-sem-perfil']) {
      await quem(db, role);
      await assert.rejects(parcial(db, 1, itens), /Sem permissão/);
      await db.exec('reset role');
    }
    await quem(db, 'entregador');
    const { r } = (await parcial(db, 1, itens, { status_pagamento: 'pago', forma_pagamento_real: 'dinheiro', data_pagamento: '2026-09-21' })).rows[0];
    assert.equal(Number(r.valor), 5 * 10 + 4 * 25);
    assert.equal(r.status_pagamento, 'pago');
    assert.equal(r.forma_pagamento_real, 'dinheiro');
  } finally { await db.close(); }
});

test('Postgres: a nova permissão não abre brechas para o entregador', async () => {
  const db = await bancoComRegrasAtuais();
  try {
    await db.exec(lerMigration('20260928170000_partial_delivery.sql'));
    await novoPedido(db);
    await quem(db, 'entregador');
    // Continua sem poder mexer em valor, descrição ou itens direto na tabela.
    await assert.rejects(db.exec("update public.pedidos set valor=1, status='entregue' where id=1"), /entregador só pode concluir/);
    await assert.rejects(db.exec("update public.pedidos set descricao='x', status='entregue' where id=1"), /entregador só pode concluir/);
    await assert.rejects(db.exec("update public.pedidos set vendedor='admin', status='entregue' where id=1"), /entregador só pode concluir/);
    assert.equal((await db.query("update public.itens_pedido set qtd=1 returning id")).rows.length, 0, 'sem permissão de alterar itens');
    assert.equal((await db.query('delete from public.itens_pedido returning id')).rows.length, 0, 'sem permissão de apagar itens');
    // O sinal da entrega parcial só vale dentro da função e para o pedido dela.
    await db.exec('reset role');
    assert.equal((await db.query("select coalesce(current_setting('kg.entrega_parcial', true), '') as v")).rows[0].v, '');
    // A entrega completa antiga continua igual.
    await quem(db, 'entregador');
    const antiga = (await db.query('select public.concluir_entrega(1,$1::jsonb) as r', [dados()])).rows[0].r;
    assert.equal(antiga.status, 'entregue');
    assert.equal(Number(antiga.valor), 200);
  } finally { await db.close(); }
});

test('Migration de entrega parcial: escopo mínimo e sem apagar dados', () => {
  const sql = lerMigration('20260928170000_partial_delivery.sql');
  assert.match(sql, /add column qtd_pedida integer;/);
  assert.match(sql, /security definer set search_path = ''/);
  assert.match(sql, /revoke all on function public\.concluir_entrega_parcial\(bigint,jsonb,jsonb\) from public, anon;/);
  assert.match(sql, /grant execute on function public\.concluir_entrega_parcial\(bigint,jsonb,jsonb\) to authenticated;/);
  assert.doesNotMatch(sql, /drop table|truncate|drop column|delete from public\.(pedidos|clientes|produtos)\b/i);
  assert.doesNotMatch(sql, /create or replace function public\.concluir_entrega\(/, 'concluir_entrega não muda');
});
