create table public.historico_pedidos (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  acao text not null check (acao in ('criado', 'editado', 'entregue', 'pagamento')),
  alterado_por text not null,
  campos text[] not null default '{}',
  antes jsonb,
  depois jsonb,
  criado_em timestamptz not null default now()
);

create index historico_pedidos_pedido_data_idx
on public.historico_pedidos (pedido_id, criado_em desc);

alter table public.historico_pedidos enable row level security;

revoke all on public.historico_pedidos from anon, authenticated;
grant select on public.historico_pedidos to authenticated;

create policy "admin consulta historico de pedidos"
on public.historico_pedidos for select
to authenticated
using ((select private.app_role()) = 'admin');

create policy "vendedor consulta historico dos proprios pedidos"
on public.historico_pedidos for select
to authenticated
using (
  (select private.app_role()) = 'vendedor'
  and exists (
    select 1
    from public.pedidos
    where pedidos.id = historico_pedidos.pedido_id
      and pedidos.vendedor = (select private.app_login())
  )
);

create or replace function private.registrar_historico_pedido()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  acao_registrada text;
  campos_alterados text[] := '{}';
  autor text;
begin
  autor := coalesce(private.app_login(), new.vendedor, current_user);

  if tg_op = 'INSERT' then
    acao_registrada := 'criado';
  else
    select coalesce(array_agg(chave order by chave), '{}')
      into campos_alterados
    from jsonb_each(to_jsonb(new)) as atual(chave, valor)
    where atual.valor is distinct from to_jsonb(old) -> chave
      and chave <> 'created_at';

    if cardinality(campos_alterados) = 0 then
      return new;
    end if;

    acao_registrada := case
      when old.status is distinct from new.status and new.status = 'entregue' then 'entregue'
      when old.status_pagamento is distinct from new.status_pagamento
        or old.forma_pagamento_real is distinct from new.forma_pagamento_real
        or old.data_pagamento is distinct from new.data_pagamento then 'pagamento'
      else 'editado'
    end;
  end if;

  insert into public.historico_pedidos
    (pedido_id, acao, alterado_por, campos, antes, depois)
  values
    (new.id, acao_registrada, autor, campos_alterados,
     case when tg_op = 'UPDATE' then to_jsonb(old) end,
     to_jsonb(new));

  return new;
end;
$$;

revoke all on function private.registrar_historico_pedido() from public, anon, authenticated;

create trigger pedidos_registrar_historico
after insert or update on public.pedidos
for each row execute function private.registrar_historico_pedido();

insert into public.historico_pedidos
  (pedido_id, acao, alterado_por, depois, criado_em)
select id, 'criado', coalesce(vendedor, 'sistema'), to_jsonb(pedidos), coalesce(created_at, now())
from public.pedidos;
