-- Acerto de comissão registrado.
--
-- Quando o administrador paga a comissão de um vendedor por um período, registra
-- o acerto: o banco guarda, pedido a pedido, o que entrou na conta (unidades e
-- valor). Se depois houver devolução, correção ou uma entrega lançada com data
-- daquele período, o relatório compara com o que foi guardado e mostra a
-- diferença, para acertar no próximo pagamento. Nada é travado: corrigir pedidos
-- continua livre.
--
-- Mudança aditiva: uma tabela nova (vazia) e uma função nova. Nenhum pedido é
-- alterado e o aplicativo antigo continua funcionando.

create table public.acertos_comissao (
  id bigint generated by default as identity primary key,
  vendedor text not null,
  tipo text not null check (tipo in ('semanal', 'quinzenal', 'mensal')),
  ini date not null,
  fim date not null,
  -- [{"id", "cliente", "data", "unidades", "valor"}] de cada pedido entregue no período
  pedidos jsonb not null check (jsonb_typeof(pedidos) = 'array'),
  unidades numeric not null check (unidades >= 0),
  total numeric not null check (total >= 0),
  registrado_por text not null,
  registrado_em timestamptz not null default now(),
  constraint acertos_comissao_periodo_check check (fim >= ini)
);

create index acertos_comissao_periodo_idx
  on public.acertos_comissao (vendedor, ini, fim, registrado_em desc);

-- Histórico: ninguém altera nem apaga pela API. Um acerto refeito é um registro novo.
alter table public.acertos_comissao enable row level security;
revoke all on public.acertos_comissao from public, anon, authenticated;
grant select on public.acertos_comissao to authenticated;

create policy acertos_comissao_select on public.acertos_comissao for select to authenticated
using (
  (select private.app_role()) = 'admin'
  or ((select private.app_role()) = 'vendedor' and vendedor = (select private.app_login()))
);

-- O próprio banco monta a lista do acerto (só o que está confirmado no servidor),
-- com a mesma regra do relatório: entregue, do vendedor, com a data real da
-- entrega (ou a prevista, nos pedidos antigos sem data real) dentro do período.
create or replace function public.registrar_acerto(p_vendedor text, p_tipo text, p_ini date, p_fim date)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  lista jsonb;
  acerto public.acertos_comissao;
begin
  if coalesce(private.app_role(), '') <> 'admin' then
    raise exception 'Só o administrador registra acertos';
  end if;
  if coalesce(p_vendedor, '') = '' then
    raise exception 'Escolha o vendedor do acerto';
  end if;
  if coalesce(p_tipo, '') not in ('semanal', 'quinzenal', 'mensal') then
    raise exception 'Tipo de período inválido';
  end if;
  if p_ini is null or p_fim is null or p_fim < p_ini then
    raise exception 'Período inválido';
  end if;
  if p_ini > (statement_timestamp() at time zone 'America/Sao_Paulo')::date then
    raise exception 'Este período ainda não começou';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'id', p.id,
      'cliente', coalesce(c.nome, 'Cliente'),
      'data', coalesce(p.data_entregue_em, p.data_entrega),
      'unidades', coalesce((select sum(i.qtd) from public.itens_pedido i where i.pedido_id = p.id), 0),
      'valor', coalesce(p.valor, 0)
    ) order by p.id), '[]'::jsonb)
    into lista
  from public.pedidos p
  left join public.clientes c on c.id = p.cliente_id
  where p.status = 'entregue'
    and p.vendedor = p_vendedor
    and coalesce(p.data_entregue_em, p.data_entrega) between p_ini and p_fim;

  insert into public.acertos_comissao (vendedor, tipo, ini, fim, pedidos, unidades, total, registrado_por)
  values (
    p_vendedor, p_tipo, p_ini, p_fim, lista,
    coalesce((select sum((e->>'unidades')::numeric) from jsonb_array_elements(lista) e), 0),
    coalesce((select sum((e->>'valor')::numeric) from jsonb_array_elements(lista) e), 0),
    coalesce(private.app_login(), 'admin')
  )
  returning * into acerto;
  return to_jsonb(acerto);
end; $$;

revoke all on function public.registrar_acerto(text, text, date, date) from public, anon;
grant execute on function public.registrar_acerto(text, text, date, date) to authenticated;
